### ISSUE TITLE
Add support for setting the first day of the week

### ISSUE THREAD

**Issue by GramThanos** [GramThanos/jsCalendar#1]
I need to implement an option for setting the first day of the week (now Sunday is the first but Monday is also a popular choise).

I was thinking about that when I first codded the library but at the time I thought that it was not that important... well I was wrong because as @HasanDelibas mentions on his [fork](https://github.com/HasanDelibas/jsCalendar/commit/40ce14b748ce014676b9b7d5a93c476a7c1bba37), this may not be the case for all the countries.

**Comment by GramThanos** [comment]
Added on commit 6c3a3734864af8610341d41913a374d5d67c39e8
It needs testing.

**Comment by GramThanos** [comment]
Bugged on version 1.3-rc.1
Days numbers are shift 1 day later

**Comment by GramThanos** [comment]
Support added. Bugs were fixed.
Commit 7ee7ebd349a484038500751a61ee46fa359b1825

**Comment by hasandelibas** [comment]
Hey brother. Thank you. Sorry i didn't see your email. Thank you. I use in
my web site your name for thansk :)

**Comment by GramThanos** [comment]
Thanks! No problem.
