### ISSUE TITLE
Publishing to npm and Unpkg CDN

### ISSUE THREAD

**Issue by opsydev** [GramThanos/jsCalendar#10]
Hey,

I was wondering if there is a reason this isn't available through npm? I am more than happy to help you get set up if you would like.

**Comment by GramThanos** [comment]
Since now we have no bugs (hopefully) I was going to submit the library to CDN sites and such.

I was sceptical about npm because I personally have not tried any client library through it, but since other people use them, I should submit it there too.

Thanks for the reminder. :)

**Comment by GramThanos** [comment]
IT JUST GOT REAL!

https://www.npmjs.com/package/simple-jscalendar

If you got any tip over the file structure or the content of README.md please let me know.

---
"jscalendar" was not available (because it is similar to the "calendar.js" package)... so as you can see, I used "simple-jscalendar".

**Comment by opsydev** [comment]
🎉 🎉 🎉 

I would just add the note about the node package name in the install section of the README!

**Comment by crobinson42** [comment]
The npm package does not export anything so a `require` or `import` pull nothing from this npm module. It needs a UMD webpack bundle pipeline or similar.

**Comment by crobinson42** [comment]
Right now, the only way to use this in project that is built/bundled is to use a CDN (https://unpkg.com/simple-jscalendar@1.4.2/source/jsCalendar.js) which will set `jsCalendar` on the window object - it would be much more convenient to be able to dynamically import this package via Webpack UMD lib bundle. One pro to this is initial loads can be smaller and faster for users and the bundled app can dynamically import `jsCalendar` when it's needed instead of at the begining/initial load.

**Comment by GramThanos** [comment]
I don't know what's the default (or the most popular) way to structure you npm package for use as an web page resource and also I am not familiar with what you describe.
But I will investigate it.

**Comment by crobinson42** [comment]
Here’s what it would like to use as your webpack.config.js file:


module.exports = {
  entry: {
    main: './lib/index.js',
    example: './lib/example/index.js'
  },
  output: {
    path: path.resolve(__dirname, "dist"),
    filename: "bundle.js",
    libraryTarget: ‘umd'
  }
};


Then change your package.json “main” field to point to the bundle file in output.path (“dist/bundle.js”).

**Comment by bandantonio** [comment]
So, what is the proper way of using `jsCalendar` via npm?

I'm trying to use it in my JS project, but I'm stuck on `require` step:
```
const jsCalendar = require('simple-jscalendar');
let div = document.getElementById('calendar');
jsCalendar.new(div);
```
This gives the error:
```
Uncaught TypeError: jsCalendar.new is not a function
```

The funny thing is that once `require` is added, IntelliSense in VSCode sees all the methods of `jsCalendar` properly.

When adding the code directly to html file as described in the [Getting Started](https://gramthanos.github.io/jsCalendar/docs.html#getting-started) section, everything works as expected. But actually, I don't want to use this approach.

@crobinson42 as I understood, you managed to get this work via CDN url. Could you please describe your steps?

**Comment by crobinson42** [comment]
@bandantonio the project does not export anything either in commonjs or commonjs2 module pattern it only sets a global - until the lib author adds a Webpack UMD bundle distribution then you're only option is using a `script` tag in your html and accessing the calendar via the global variable.

Use unpkg.com CDN for your script and css <link /> resources - https://unpkg.com/simple-jscalendar@1.4.2/

**Comment by GramThanos** [comment]
### Sum up on the Issue.

So, first of all, I think it is pretty clear that this is a javascript browser library. Using `require` to load it, should be clear that it is wrong :P (`require` is for calling code running on the server not on the client).

Most popular front-end libraries on npm just provide a way to auto install and get the library. To use them **you have to manually copy the source files on your js and css folders**. A better solution would be **using Webpack** on your project to handle all your js and css files (but this **is up to you**).

~~There is currently no CDN for the library (not enought stars), so @crobinson42 suggested getting a CDN like usage from `https://unpkg.com/simple-jscalendar/`.~~ (edit: I haven't done my research on unpkg.com at the time so I could not suggest it as a CDN)

### NPM example usage
```
npm i simple-jscalendar

# Copy libary files to your resources folders
cp ./node_modules/simple-jscalendar/source/jsCalendar.js ./js/jsCalendar.js
cp ./node_modules/simple-jscalendar/source/jsCalendar.css ./css/jsCalendar.css

# Maybe copy a language and a theme too
cp ./node_modules/simple-jscalendar/source/jsCalendar.lang.gr.js ./js/jsCalendar.lang.gr.js
cp ./node_modules/simple-jscalendar/themes/jsCalendar.clean.css ./css/jsCalendar.clean.css
```

**Comment by GramThanos** [comment]
### Unpkg.com CDN

Special thanks to @crobinson42 that suggested using [unpkg.com](https://unpkg.com/) as a CDN.

As their website states:

> unpkg is a fast, global content delivery network for everything on npm.

Thus, you can use their CDN service to load the library. I would suggest adding the `integrity` attribute on each file that loads from a CDN (just to be sure). You can find an integrity hash for each file at the `CDN full demo.html` example [here](https://github.com/GramThanos/jsCalendar/blob/master/demos/cdn%20full%20demo.html).

```html
<!-- jsCalendar v1.4.3 Javascript and CSS -->
<script src="https://unpkg.com/simple-jscalendar@1.4.3/source/jsCalendar.min.js" integrity="sha384-JqNLUzAxpw7zEu6rKS/TNPZ5ayCWPUY601zaig7cUEVfL+pBoLcDiIEkWHjl07Ot" crossorigin="anonymous"></script>
<link rel="stylesheet" href="https://unpkg.com/simple-jscalendar@1.4.3/source/jsCalendar.min.css" integrity="sha384-+OB2CadpqXIt7AheMhNaVI99xKH8j8b+bHC8P5m2tkpFopGBklD3IRvYjPekeWIJ" crossorigin="anonymous">
```
