### ISSUE TITLE
height and width?

### ISSUE THREAD

**Issue by elmer120** [GramThanos/jsCalendar#15]
It's possible to set height and width?
or change the calendar for get minor space?

sorry for my bad english ;)

**Comment by GramThanos** [comment]
Well... I was on my PC... so... IT JUST GOT REAL!
😆

**Comment by scottrpaterson** [comment]
For anyone that struggles with this. Try this:

.jsCalendar tbody td, .jsCalendar thead .jsCalendar-week-days th, .jsCalendar tbody td {
    font-size: 14px !important;
    width: 45px !important;
    height: 45px !important;
}
