### ISSUE TITLE
Chinese Date, day format issue D and DDD

### ISSUE THREAD

**Issue by bjouannes87** [GramThanos/jsCalendar#18]
Hi ! Chinese days are displayed as 星期天, 星期一, 星期二, 星期三, 星期四, 星期五, 星期六 etc. When I chose dayFormat: "D" it shows only 星 for all days. It should be 天, 一, 二, 三, 四, 五, 六.

星期 = means week
一 = means one
星期一 = means monday

Also, I think it's better to use 日 instead of 天 for Sunday

For your reference here is a Baidu link where you can see how they display their calendar

https://www.baidu.com/s?wd=%E6%97%A5%E5%8E%86&rsv_spt=1&rsv_iqid=0xf46a07ef0001d2ab&issp=1&f=8&rsv_bp=1&rsv_idx=2&ie=utf-8&rqlang=cn&tn=baiduhome_pg&rsv_enter=0&rsv_t=44ae%2Fk0X71DquF6AMon82rVl9jwUtj8xFgIl7E14LGjaF6XLxoG%2F%2BdyAcGy9zkCi7oyd&oq=P.R.%2526lt%253B%25E6%2597%25A5%25E5%258E%2586&inputT=385&rsv_pq=de14491500025af3&rsv_sug3=3&rsv_sug1=2&rsv_sug7=100&rsv_sug2=0&rsv_sug4=385

Thanks a lot for your work, the calendar is working very well.

**Comment by GramThanos** [comment]
I was thinking of a good solution the last days... so I added support for custom handlers on the language file. I edited the `jsCalendar.lang.zh.js` to overwrite the default rules for `D` and `DD` and display the 3rd char instead.

What do you think? Should we make any other changes on the Chinese translation?

PS: Is it rude if I translate `baidu` into english using `google` ?

**Comment by bjouannes87** [comment]
Hello, 
I just checked the code of `jsCalendar.lang.zh.js` and I see a problem on the days : 

"星期天", // sunday
"星期一",
"星期二",
"星期三",
"星期四",
"星期五",
"星期日" //  sunday

it should be : 
"星期日", // sunday
"星期一", 
"星期二",
"星期三", 
"星期四",
"星期五",
"星期六" // saturday

For dayStringParser function it looks good but I didn't test it. I'll test the calendar this weekend and give you the feedback.

I'm not sure to understand your last question. You can translate search you make on Baidu using Google but be careful because results are not always accurate (although, it has been strongly improved recently with new Google neuronal algorithm for translations)

**Comment by GramThanos** [comment]
Hahaha, I made the mistake.
You said `I think it's better to use 日 instead of 天 for Sunday` and I meshed up the `天` with `六`.

**Comment by GramThanos** [comment]
My last question was a joke because Google and Baidu are opponents.
