### ISSUE TITLE
Issue with selected days

### ISSUE THREAD

**Issue by rodrigoetoh** [GramThanos/jsCalendar#19]
Hello, how you doing?

I found a bug when using selected days, the issue is that you use time to keep track of selected days, but you use it's TIME, without reseting the hour of the date element, whereas you do reset it when checking whether it is a selected day or not. This causes some days to not being marked as selected when drawing the calendar.

I'm attaching some examples.

A fix to that would be reseting the hours when you get the visible dates at:

```javascript
JsCalendar.prototype._getVisibleDates = function(date) {

	// ...

	// Set day to month's first
	day = new Date(first.getTime());
	day.setHours(0, 0, 0, 0);
	// This month's days
	do {
	// Add page on back of the list
	dates.push(new Date(day.getTime()));
	// Calculate next day
	day.setDate(day.getDate() + 1);
	day.setHours(0, 0, 0, 0);
	// Repeat until next month
	} while (day.getDate() !== 1);

	// ...
```

Best regards,
Etoh.

![screenshot_6](https://user-images.githubusercontent.com/2234418/41105377-fb56381a-6a43-11e8-8800-a7a130fc7983.jpg)
![screenshot_7](https://user-images.githubusercontent.com/2234418/41105378-fb7aa6d2-6a43-11e8-9967-a5fb866e51b5.jpg)
![screenshot_8](https://user-images.githubusercontent.com/2234418/41105379-fc07e7e0-6a43-11e8-8daf-0ca75db6fc5b.jpg)

**Comment by GramThanos** [comment]
I am fine! Thanks! How are you?

Commit 4741bbd071a71af856db6bf72137da3aaf6fad58
