### ISSUE TITLE
Support for changing the calendar's HTML structure

### ISSUE THREAD

**Issue by GramThanos** [GramThanos/jsCalendar#2]
Support for changing the calendar's HTML structure will enable more options for theme developers.
The current stucture is a simple HTML table. This limits the possible themes layouts.

**Comment by hasandelibas** [comment]
Yes. thank you. :)

**Comment by GramThanos** [comment]
This is a functionality that I want to implement on the future.
The html code of the calendar is a HTML table by default.
But to be able to create other HTML structures that has to be changable, so I am thinking about implementing a dynamic theme support. That you (the coder/user) will define the function that renders the calendar.

**Comment by GramThanos** [comment]
Closed 4 now 😢
