### ISSUE TITLE
min-date on dynamic calendar?

### ISSUE THREAD

**Issue by TimUK** [GramThanos/jsCalendar#22]
I can see that you can set a min date for the auto created calendar like so

 `data-min="01/01/2017"`

but how can I set a min date for a dynamically created calendar? Can't see an option or method for it.

**Comment by GramThanos** [comment]
Sorry my fault! I forgot to add them to the documentation.

There are 2 methods for that, `myCalendar.min(<date>);` and `myCalendar.max(<date>);`.
So you can use `myCalendar.min("01/01/2017");`

I added an example [min max methods example](../blob/master/examples/javascript%20methods%20min%20max.html)

**Comment by TimUK** [comment]
Ah amazing thanks, I was trying to use it in the options! Works perfect.

**Comment by GramThanos** [comment]
I am going to leave this open until I fix the documentation 😄

**Comment by GramThanos** [comment]
Methods were added on the documentation.
https://gramthanos.github.io/jsCalendar/docs.html#javascript-method-min-max

Also, I improved the examples on all the parameters.
