### ISSUE TITLE
About selecting date styling

### ISSUE THREAD

**Issue by takuminaoya** [GramThanos/jsCalendar#26]
is it possible if you add the option to set a different color for each selected date?
or do you know the way to do that?

if so can i hope you can tell me how :smile:

**Comment by GramThanos** [comment]
Rainbows! 🌈 

I knew you will start asking for plugins... (you are the second guy). I will have to release a plugin system on version 2.
For now you will have to stick with the demos 😄 

So, I created a demo for you. It implements the awesome method `colorfulSelect` that you can use.
Check it out! https://github.com/GramThanos/jsCalendar/blob/master/demos/colorful%20selects.html

![image](https://user-images.githubusercontent.com/14858959/47789168-8382a480-dd1c-11e8-9cc6-006548e4d0ec.png)

**Comment by takuminaoya** [comment]
thank you so much :smile:
