### ISSUE TITLE
Extra weeks in some months

### ISSUE THREAD

**Issue by Yur-ok** [GramThanos/jsCalendar#29]
Hi! You have a great plugin.
But it has extra weeks in some months.
For example on you main page of project has description with March month.
Off cause some time there needs 6 rows to display the month. 
But in other cases (e.g. March) there is enough 5 rows.
Is there any way to switch off this extra lines?

**Comment by GramThanos** [comment]
No, there is no option to switch off the extra lines.

But you can always hack the code 😄 .
So you can just add this code just under the library script, and it will implement what you ask for every calendar in your page.

```javascript
jsCalendar.prototype._update_orgnl = jsCalendar.prototype._update;
jsCalendar.prototype._update = function() {
	this._update_orgnl();

	// If last row is only for next month
	if (this._elements.bodyCols[35].className == 'jsCalendar-next') {
		// Hide last row
		this._elements.bodyRows[5].style.display = 'none';
	}
	else {
		this._elements.bodyRows[5].style.display = '';
	}
}
```

EDIT: Shame on me! There was an error on the code that Yur-ok found out later. (I edited the code to avoid future confusion.)

**Comment by Yur-ok** [comment]
Thanks a lot!
I'll try it soon.

==================
Well I got this error:
```
jsCalendar.js:1373 Uncaught ReferenceError: cal is not defined
    at JsCalendar.jsCalendar._update (jsCalendar.js:1373)
    at JsCalendar._construct (jsCalendar.js:61)
    at new JsCalendar (jsCalendar.js:40)
    at Function.JsCalendar.autoFind (jsCalendar.js:1163)
    at eval (jsCalendar.js:1362)
```
I added your peace of code at the end of  jsCalendar.js file.
Am I right?

**Comment by Yur-ok** [comment]
Well I figured out it myself!!!
I just replaced cal > this!
And it worked as expected!

**Comment by GramThanos** [comment]
Oups... My mistake sorry!
So... you end up hacking the code :laughing:
