### ISSUE TITLE
Navigation-Problem with min-Date and start-Date

### ISSUE THREAD

**Issue by Chris8934** [GramThanos/jsCalendar#30]
Hi,

if you set an min-Date and start-Date which is not the first day of month, i could not navigate back to the first month. Example: If i set this two dates to 2/05/2018 and navigate to June, i could not navigate back to may. If i set it to 1/05/2018 it works like expected.

var calendar = jsCalendar.new(document.getElementById("calendar"), "2/05/2018" , {monthFormat : "month YYYY", language: "de", min: '2/05/2018', max: '31/12/2018', firstDayOfTheWeek : '2' });

Not such a big problem, just in case somebody needs a wokaround set the dates to 1/m/Y

**Comment by GramThanos** [comment]
Thanks for reporting it!
Patched 57e7b96cf2a7ec1bbffdb7f3cd068ac1ccd4eb07
