### ISSUE TITLE
Making 2 calendars

### ISSUE THREAD

**Issue by adnjoo** [GramThanos/jsCalendar#34]
![bug](https://user-images.githubusercontent.com/22807629/52255010-9a541b00-294b-11e9-9562-8d600d14d834.png)
Hi I tried to make a new calendar but I end up getting two calendars..

`

<html><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"><script src="jsCalendar.js" ></script>
<link rel="stylesheet" href="jsCalendar.css" >

<script type="text/javascript">
    // Get the element
    var element = document.getElementById("my-calendar");
    // Create the calendar
    var myCalendar = jsCalendar.new(element);
    // Get the inputs
    var inputA = document.getElementById("my-input-a");
    var inputB = document.getElementById("my-input-b");
    // Add events
    myCalendar.onDateClick(function(event, date){
        inputA.value = date.toString();
    });
    myCalendar.onMonthChange(function(event, date){
        inputB.value = date.toString();
    });
</script>

		<title>jsCalendar Demo</title>
		<meta name="description" content="jsCalendar demo - date events">
		<meta name="author" content="GramThanos">

		
		<link rel="stylesheet" type="text/css" href="file:///C:/Users/Andrew%20Njoo/css/jsCalendar.min.css">
		<link rel="stylesheet" type="text/css" href="file:///C:/Users/Andrew%20Njoo/css/themes/jsCalendar.clean.min.css">
		<script type="text/javascript" src="file:///C:/Users/Andrew%20Njoo/js/jsCalendar.min.js"></script>

		

		
		<style>
			html, body {
				font-family: "Century Gothic", CenturyGothic, AppleGothic, sans-serif;
			}
			.description {
				text-align: center;
				padding-bottom: 40px;
			}
			.jsCalendar.clean-theme tbody td.jsCalendar-previous, .jsCalendar.clean-theme tbody td.jsCalendar-next {
				color: #000;
				opacity: 0.2;
			}
			#wrapper {
				margin: 0 auto;
				width: 800px;
				box-shadow: 0px 0px 2px rgba(0, 0, 0, 0.4);
			}
			#wrapper .jsCalendar table {
				box-shadow: none;
			}
			.clear {
				clear: both;
			}
			#events-calendar {
				float: left;
			}
			#events {
				float: left;
				width: 435px;
				margin: 10px 20px 10px 5px;
			}
			#events .title {
				padding: 5px 0px;
				text-align: center;
				font-weight: bold;
				border-bottom: 1px solid rgba(0, 0, 0, 0.4);
			}
			#events .subtitle {
				padding: 5px 0px;
				font-size: 14px;
				text-align: center;
				color: #888;
			}
			#events .list {
				height: 250px;
				overflow-y: auto;
				border-bottom: 1px solid rgba(0, 0, 0, 0.2);
			}
			#events .list .event-item {
				line-height: 24px;
				min-height: 24px;
				padding: 2px 5px;
				border-top: 1px solid rgba(0, 0, 0, 0.2);
			}
			#events .list .event-item .close {
				font-family: Tahoma, Geneva, sans-serif;
				font-weight: bold;
				font-size: 12px;
				color: #000;
				border-radius: 8px;
				height: 14px;
				width: 14px;
				line-height: 12px;
				text-align: center;
				float: right;
				border: 1px solid rgba(0, 0, 0, 0.5);
				padding: 0px;
				margin: 5px;
				display: block;
				overflow: hidden;
				background: #F44336;
				cursor: pointer;
			}
			#events .action {
				text-align: right;
			}
			#events .action input {
				padding: 0px 5px;
				font-size: 12px;
				margin: 10px 5px;
				border: 1px solid #999999;
				height: 28px;
				line-height: 28px;
				width: 120px;
				background: #f8f8f8;
				color: black;
				cursor: pointer;
				transition: all 0.2s;
			}
			#events .action input:hover {
				background: #eee;
				border: 1px solid #000;
				box-shadow: 0px 0px 3px rgba(0, 0, 0, 0.2);
			}
			.version {
				font-size: 12px;
				width: 800px;
				margin: 0 auto;
				text-align: right;
			}
		</style>
	</head>

  <body class="vsc-initialized">
		<div class="description">
			<div style="font-size: 1.4em;">Date Events</div>
			<div>Demo calendar date events using jsCalendar</div>
		</div>

		
		<div id="wrapper">
			
			<div id="events-calendar" class="clean-theme jsCalendar"><table><thead><tr class="jsCalendar-title-row"><th colspan="7" class="jsCalendar-title"><div class="jsCalendar-title-left"><div class="jsCalendar-nav-left"></div></div><div class="jsCalendar-title-name">February</div><div class="jsCalendar-title-right"><div class="jsCalendar-nav-right"></div></div></th></tr><tr class="jsCalendar-week-days"><th>S</th><th>M</th><th>T</th><th>W</th><th>T</th><th>F</th><th>S</th></tr></thead><tbody><tr><td class="jsCalendar-previous">27</td><td class="jsCalendar-previous">28</td><td class="jsCalendar-previous">29</td><td class="jsCalendar-previous">30</td><td class="jsCalendar-previous">31</td><td>1</td><td>2</td></tr><tr><td>3</td><td>4</td><td class="jsCalendar-selected jsCalendar-current">5</td><td>6</td><td>7</td><td>8</td><td>9</td></tr><tr><td>10</td><td>11</td><td>12</td><td>13</td><td>14</td><td>15</td><td>16</td></tr><tr><td>17</td><td>18</td><td>19</td><td>20</td><td>21</td><td>22</td><td>23</td></tr><tr><td>24</td><td>25</td><td>26</td><td>27</td><td>28</td><td class="jsCalendar-next">1</td><td class="jsCalendar-next">2</td></tr><tr><td class="jsCalendar-next">3</td><td class="jsCalendar-next">4</td><td class="jsCalendar-next">5</td><td class="jsCalendar-next">6</td><td class="jsCalendar-next">7</td><td class="jsCalendar-next">8</td><td class="jsCalendar-next">9</td></tr></tbody></table></div>
			
			<div id="events"><div class="title">05/02/2019</div><div class="subtitle">1 event</div><div class="list"><div class="event-item">1. went to gym<div class="close">×</div></div></div><div class="action"><input type="button" value="Add"></div></div>
			
			<div class="clear"></div>
		</div>
		<div class="clear"></div>

		
		<script type="text/javascript">
			// Get elements
			var elements = {
				// Calendar element
				calendar : document.getElementById("events-calendar"),
				// Input element
				events : document.getElementById("events")
			}

			// Create the calendar
			elements.calendar.className = "clean-theme";
			var calendar = jsCalendar.new(elements.calendar);

			// Create events elements
			elements.title = document.createElement("div");
			elements.title.className = "title";
			elements.events.appendChild(elements.title);
			elements.subtitle = document.createElement("div");
			elements.subtitle.className = "subtitle";
			elements.events.appendChild(elements.subtitle);
			elements.list = document.createElement("div");
			elements.list.className = "list";
			elements.events.appendChild(elements.list);
			elements.actions = document.createElement("div");
			elements.actions.className = "action";
			elements.events.appendChild(elements.actions);
			elements.addButton = document.createElement("input");
			elements.addButton.type = "button";
			elements.addButton.value = "Add";
			elements.actions.appendChild(elements.addButton);

			var events = {};
			var date_format = "DD/MM/YYYY";
			var current = null;

			var showEvents = function(date){
				// Date string
				var id = jsCalendar.tools.dateToString(date, date_format, "en");
				// Set date
				current = new Date(date.getTime());
				// Set title
				elements.title.textContent = id;
				// Clear old events
				elements.list.innerHTML = "";
				// Add events on list
				if (events.hasOwnProperty(id) && events[id].length) {
					// Number of events
					elements.subtitle.textContent = events[id].length + " " + ((events[id].length > 1) ? "events" : "event");

					var div;
					var close;
					// For each event
					for (var i = 0; i < events[id].length; i++) {
						div = document.createElement("div");
						div.className = "event-item";
						div.textContent = (i + 1) + ". " + events[id][i].name;
						elements.list.appendChild(div);
						close = document.createElement("div");
						close.className = "close";
						close.textContent = "×";
						div.appendChild(close);
						close.addEventListener("click", (function (date, index) {
							return function () {
								removeEvent(date, index);
							}
						})(date, i), false);
					}
				} else {
					elements.subtitle.textContent = "No events";
				}
			};

			var removeEvent = function (date, index) {
				// Date string
				var id = jsCalendar.tools.dateToString(date, date_format, "en");

				// If no events return
				if (!events.hasOwnProperty(id)) {
					return;
				}
				// If not found
				if (events[id].length <= index) {
					return;
				}

				// Remove event
				events[id].splice(index, 1);

				// Refresh events
				showEvents(current);

				// If no events uncheck date
				if (events[id].length === 0) {
					calendar.unselect(date);
				}
			}

			// Show current date events
			showEvents(new Date());

			// Add events
			calendar.onDateClick(function(event, date){
				// Update calendar date
				calendar.set(date);
				// Show events
				showEvents(date);
			});

			elements.addButton.addEventListener("click", function(){
				// Get event name
				var names = ["John", "Bob", "Anna", "George", "Harry", "Jack", "Alexander"];
				var name = prompt(
					"Event info",
					names[Math. floor(Math.random() * names.length)] + "'s birthday."
				);

				//Return on cancel
				if (name === null || name === "") {
					return;
				}

				// Date string
				var id = jsCalendar.tools.dateToString(current, date_format, "en");

				// If no events, create list
				if (!events.hasOwnProperty(id)) {
					// Select date
					calendar.select(current);
					// Create list
					events[id] = [];
				}

				// Add event
				events[id].push({name : name});

				// Refresh events
				showEvents(current);
			}, false);
		</script>

		<br>

</body></html>
`

**Comment by GramThanos** [comment]
Hello Andrew,
I think you are confused about how HTML and Javascript works.

Your calendar element is wrong (you copied a rendered calendar code), you are not supposed to copy the page code after its execution because it is changed.

Next time, when you face an problem try to debug your code or start again with a blank document.


Your code:
```html
<!-- Calendar element -->
<div id="events-calendar" class="clean-theme jsCalendar"><table><thead><tr class="jsCalendar-title-row"><th colspan="7" class="jsCalendar-title"><div class="jsCalendar-title-left"><div class="jsCalendar-nav-left"></div></div><div class="jsCalendar-title-name">February</div><div class="jsCalendar-title-right"><div class="jsCalendar-nav-right"></div></div></th></tr><tr class="jsCalendar-week-days"><th>S</th><th>M</th><th>T</th><th>W</th><th>T</th><th>F</th><th>S</th></tr></thead><tbody><tr><td class="jsCalendar-previous">27</td><td class="jsCalendar-previous">28</td><td class="jsCalendar-previous">29</td><td class="jsCalendar-previous">30</td><td class="jsCalendar-previous">31</td><td>1</td><td>2</td></tr><tr><td>3</td><td>4</td><td class="jsCalendar-selected jsCalendar-current">5</td><td>6</td><td>7</td><td>8</td><td>9</td></tr><tr><td>10</td><td>11</td><td>12</td><td>13</td><td>14</td><td>15</td><td>16</td></tr><tr><td>17</td><td>18</td><td>19</td><td>20</td><td>21</td><td>22</td><td>23</td></tr><tr><td>24</td><td>25</td><td>26</td><td>27</td><td>28</td><td class="jsCalendar-next">1</td><td class="jsCalendar-next">2</td></tr><tr><td class="jsCalendar-next">3</td><td class="jsCalendar-next">4</td><td class="jsCalendar-next">5</td><td class="jsCalendar-next">6</td><td class="jsCalendar-next">7</td><td class="jsCalendar-next">8</td><td class="jsCalendar-next">9</td></tr></tbody></table></div>
```
Should be:
```html
<!-- Calendar element -->
<div id="events-calendar"></div>
```
