### ISSUE TITLE
Add support for min - max date

### ISSUE THREAD

**Issue by GramThanos** [GramThanos/jsCalendar#4]
> Is there a way to add a min date (ie: current date) and a maxdate (ie: current date = 1 year)?

Suggested by @crist-y

So, if I understand correctly, you want the calendar to be limited inside a date range.

**Comment by crist-y** [comment]
Hi,
Yes be able to define a variable minDate and maxDate, that play nice with the Date object and the rest of the script.
Where would you put it inside your script?

**Comment by crist-y** [comment]
Also I apologize if I polluted your other branch, I'm new to GitHub, and to more complex JS

**Comment by GramThanos** [comment]
Dont worry about where you post. It is just easier to track issues when they are in separate issues threads.

Yes. I will implement it.

**Comment by GramThanos** [comment]
Implemented and is now live on developer version v1.4-beta.2 for testing.

```html
<div class="auto-jsCalendar"
     data-date="01/02/2017"
     data-min="01/01/2017"
     data-max="01/03/2017"></div>
```

Full example on "/examples/parameters min-max.html" file.

**Comment by crist-y** [comment]
Excellent, thanks, will test it. Cheers!

**Comment by crist-y** [comment]
Sorry mate, but how can I access the beta, cause I always get the 1.3 version

**Comment by GramThanos** [comment]
Check if you get the correct version from here:
https://github.com/GramThanos/jsCalendar/releases/tag/v1.4-beta.2

**Comment by crist-y** [comment]
Thanks mate!
