### ISSUE TITLE
[bug] Can't select some days

### ISSUE THREAD

**Issue by misaelvillegas97** [GramThanos/jsCalendar#44]
Hi dev, well i'm trying mark selecting days on September, but all days after 08 doesn't mark it.

Only mark days between 01 and 08, everything after that, just ignore it.
Can you help me?

**Comment by GramThanos** [comment]
In what format do you specify the dates?

Here is an example that selects all the September 2019 dates:

```html
<html lang="en">
	<head>
		<meta charset="utf-8">
		<title>jsCalendar</title>
		<!-- jsCalendar v1.4.4 Javascript and CSS -->
		<script src="https://cdn.jsdelivr.net/npm/simple-jscalendar@1.4.4/source/jsCalendar.min.js" integrity="sha384-0LaRLH/U5g8eCAwewLGQRyC/O+g0kXh8P+5pWpzijxwYczD3nKETIqUyhuA8B/UB" crossorigin="anonymous"></script>
		<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/simple-jscalendar@1.4.4/source/jsCalendar.min.css" integrity="sha384-44GnAqZy9yUojzFPjdcUpP822DGm1ebORKY8pe6TkHuqJ038FANyfBYBpRvw8O9w" crossorigin="anonymous">
	</head>
	<body>
		<!-- jsCalendar element -->
		<div id="calendar"></div>

		<!-- Create the calendar -->
		<script type="text/javascript">
			// Create the calendar
			// Set as date the 1st of September
			var myCalendar = jsCalendar.new("#calendar", "01/09/2019");
			// Lets add the dates we want to select on an array
			var days2select = [];
			// Format DD/MM/YYYY is the default
			days2select.push("01/09/2019");
			// You can use D/M/YYYY too
			for (var i = 2; i <= 15; i++) {
				days2select.push( i + "/9/2019");
			}
			// Also, you can use Date objects
			days2select.push(new Date(2019, 9 - 1, 16));
			for (var i = 17; i <= 30; i++) {
				days2select.push(new Date(2019, 9 - 1, i));
			}
			// Select the dates on the array
			myCalendar.select(days2select);

			// See the generated array on the console
			console.log(days2select);
		</script>
	</body>
</html>
```

**Comment by misaelvillegas97** [comment]
Hi, yeah, that doesn't work form me, i'm using 1.4.3 version and this its the result...

**Comment by misaelvillegas97** [comment]
![image](https://user-images.githubusercontent.com/29538430/59779819-eebac000-9286-11e9-8346-e95e0959ede1.png)

**Comment by misaelvillegas97** [comment]
Paint all before 09, all next values, just ignore, in console doesnt show any error message, i'm trying selecting over console, and nothing.

**Comment by misaelvillegas97** [comment]
This it's my code

```javascript
cal.onDateClick( function( event, date ) {

	var dia_calender = date.getDate();
	var mes_calender = date.getMonth() + 1;
	var year_calender = date.getFullYear();
	var fulldate = dia_calender+"/"+mes_calender+"/"+year_calender;
	console.log("mes calendario "+mes_calender+"|");
	console.log("mes seleccionado"+ z_mes);

	var days2select = [];
	// Format DD/MM/YYYY is the default
	days2select.push("01/09/2019");
	// You can use D/M/YYYY too
	// for (var i = 2; i <= 15; i++) {
	// 	days2select.push( i + "/9/2019");
	// }
	// Also, you can use Date objects
	days2select.push(new Date(2019, 9 - 1, 16));
	for (var i = 17; i <= 30; i++) {
		days2select.push(new Date(2019, 9 - 1, i));
	}
	// Select the dates on the array
	cal.select(days2select);
});
```

**Comment by GramThanos** [comment]
I can not reproduce the problem, even with version 1.4.3, from my point of view it works.
If you want just o select a date on click, you can just use the `date` variable from the event.

```javascript
cal.onDateClick( function( event, date ) {
    cal.select(date);
});
```

**Comment by misaelvillegas97** [comment]
That's the problem, i'm doing this on an Angular project and PHP project, in both doesn't work select or mark any days on september after 08/09.

**Comment by misaelvillegas97** [comment]
Examples:
ANGULAR (v: 1.4.4):
Another month
![image](https://user-images.githubusercontent.com/29538430/59783413-182b1a00-928e-11e9-80f1-e0bd894aaaf3.png)

September
![image](https://user-images.githubusercontent.com/29538430/59783457-2b3dea00-928e-11e9-8a9d-28306f41deda.png)

PHP (v:1.4.3):
Another month
![image](https://user-images.githubusercontent.com/29538430/59783509-43ae0480-928e-11e9-9cfc-03c840ea6ace.png)

September:
![image](https://user-images.githubusercontent.com/29538430/59783525-4dd00300-928e-11e9-9089-9c46a5622bb8.png)

I've looking for a solution several weeks, but this it is my last chance jaja :(

**Comment by misaelvillegas97** [comment]
> In what format do you specify the dates?
> 
> Here is an example that selects all the September 2019 dates:
> 
> ```
> <html lang="en">
> 	<head>
> 		<meta charset="utf-8">
> 		<title>jsCalendar</title>
> 		
> 		<script src="https://cdn.jsdelivr.net/npm/simple-jscalendar@1.4.4/source/jsCalendar.min.js" integrity="sha384-0LaRLH/U5g8eCAwewLGQRyC/O+g0kXh8P+5pWpzijxwYczD3nKETIqUyhuA8B/UB" crossorigin="anonymous"></script>
> 		<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/simple-jscalendar@1.4.4/source/jsCalendar.min.css" integrity="sha384-44GnAqZy9yUojzFPjdcUpP822DGm1ebORKY8pe6TkHuqJ038FANyfBYBpRvw8O9w" crossorigin="anonymous">
> 	</head>
> 	<body>
> 		
> 		<div id="calendar"></div>
> 
> 		
> 		<script type="text/javascript">
> 			// Create the calendar
> 			// Set as date the 1st of September
> 			var myCalendar = jsCalendar.new("#calendar", "01/09/2019");
> 			// Lets add the dates we want to select on an array
> 			var days2select = [];
> 			// Format DD/MM/YYYY is the default
> 			days2select.push("01/09/2019");
> 			// You can use D/M/YYYY too
> 			for (var i = 2; i <= 15; i++) {
> 				days2select.push( i + "/9/2019");
> 			}
> 			// Also, you can use Date objects
> 			days2select.push(new Date(2019, 9 - 1, 16));
> 			for (var i = 17; i <= 30; i++) {
> 				days2select.push(new Date(2019, 9 - 1, i));
> 			}
> 			// Select the dates on the array
> 			myCalendar.select(days2select);
> 
> 			// See the generated array on the console
> 			console.log(days2select);
> 		</script>
> 	</body>
> </html>
> ```



I reproduce your example now, and have the same issue, look:
![image](https://user-images.githubusercontent.com/29538430/59784135-bf5c8100-928f-11e9-9708-100580e31fca.png)

**Comment by GramThanos** [comment]
This is so weird ... 

On my example, run on your browser console:
```javascript
console.log(myCalendar._selected);
```
It should output 
```
1569790800000, 1569704400000, 1569618000000, 1569531600000, 1569445200000, 1569358800000,
1569272400000, 1569186000000, 1569099600000, 1569013200000, 1568926800000, 1568840400000,
1568754000000, 1568667600000, 1568581200000, 1568494800000, 1568408400000, 1568322000000,
1568235600000, 1568149200000, 1568062800000, 1567976400000, 1567890000000, 1567803600000,
1567717200000, 1567630800000, 1567544400000, 1567458000000, 1567371600000, 1567285200000
```

If it does not, try to inject them and see if the calendar shows all the dates selected
```javascript
myCalendar._selected = [
1569790800000, 1569704400000, 1569618000000, 1569531600000, 1569445200000, 1569358800000,
1569272400000, 1569186000000, 1569099600000, 1569013200000, 1568926800000, 1568840400000,
1568754000000, 1568667600000, 1568581200000, 1568494800000, 1568408400000, 1568322000000,
1568235600000, 1568149200000, 1568062800000, 1567976400000, 1567890000000, 1567803600000,
1567717200000, 1567630800000, 1567544400000, 1567458000000, 1567371600000, 1567285200000
];
myCalendar.refresh();
```

**Comment by GramThanos** [comment]
I found what causes the problem, computer time zone. I will start searching for solutions.

**Comment by misaelvillegas97** [comment]
Oh, nice! That it's an excellent news. I'll be pending any update. Thank's a lot.

**Comment by GramThanos** [comment]
The bug was fixed on the development version, it needs some testing in case it produce other problems.
You can use the code below to fix the issue on your application.

Patch for versions 1.4.3 and 1.4.4 (so that you don't have to upgrade or self host the development version).

You may insert it under your `jsCalendar.js` html script tag
```html
<script type="text/javascript">
/*
	jsCalendar bug patch: dates select bug
	for versions 1.4.3 & 1.4.4 
*/
(function(){
    if (jsCalendar.version !== 'v1.4.4' && jsCalendar.version !== 'v1.4.3') {
        throw new Error('jsCalendar patch: Wrong jsCalendar version.');
    }
    // Get visible dates
    jsCalendar.prototype._getVisibleDates = function(date) {
        var tools = (jsCalendar.version === 'v1.4.4') ? jsCalendar.tools : {parseDate : this._parseDate};
        // For date
        if (typeof date === 'undefined') {
            // Get saved date
            date = this._date;
        }
        else {
            date = tools.parseDate(date);
        }

        // Visible days array
        var dates = [];
        // Get first day of the month
        var first = new Date(date.getTime());
        first.setDate(1);
        first.setHours(0, 0, 0, 0);

        // Count days of previous month to show
        var previous = first.getDay() - (this._options.firstDayOfTheWeek - 1);
        if (previous < 0) {
            previous += 7;
        }
        // Set day to month's first
        var day = new Date(first.getTime());
        // Previous month's days
        while (previous > 0) {
            // Calculate previous day
            day.setDate(day.getDate() - 1);
            day.setHours(0, 0, 0, 0);
            // Add page on frond of the list
            dates.unshift(new Date(day.getTime()));
            // Previous
            previous --;
        }

        // Set day to month's first
        day = new Date(first.getTime());
        // This month's days
        do {
            // Add page on back of the list
            dates.push(new Date(day.getTime()));
            // Calculate next day
            day.setDate(day.getDate() + 1);
            day.setHours(0, 0, 0, 0);
            // Repeat until next month
        } while (day.getDate() !== 1);

        // Next month's days
        var next = 42 - dates.length;
        // Add days left
        while (next > 0) {
            // Add page on back of the list
            dates.push(new Date(day.getTime()));
            // Calculate next day
            day.setDate(day.getDate() + 1);
            day.setHours(0, 0, 0, 0);
            // Next
            next --;
        }

        // Return days
        return dates;
    };
})();
</script>
```

**Comment by misaelvillegas97** [comment]
Thank's, have a nice day.

**Comment by GramThanos** [comment]
Thank you for reporting the problem and helping me debugging it!
I will leave this issue open until the version is released (so that other people with similar problem can apply the patch).
