### ISSUE TITLE
29/10/2017 is displayed two times

### ISSUE THREAD

**Issue by kirienzo** [GramThanos/jsCalendar#5]
Hi !
Great lib ! Thanks a lot for providing this :1st_place_medal: 
I've just noticed a bug though, if you go to the month of October 2017, the 29th is displayed two times (see screenshot). It appears on your official website, but also in my version : jsCalendar v1.3-rc.1
![screenshot from 2017-09-29 15-52-53](https://user-images.githubusercontent.com/6702588/31018996-6b7dd232-a52e-11e7-9ba0-426584e2efc4.png)

I don't know if you noticed it already, but as there was no issue about it, I thought I could create one.

Edit : tried also with the latest version jsCalendar v1.4-beta.2 and it's still there

**Comment by GramThanos** [comment]
LoL ... yeah ... this is a nice bug.
Thank you for reporting it!

It must be many versions old 😄

**Comment by GramThanos** [comment]
Also something else, can you please tell what browser/os are you using, because the "Github" menu link should be in the same line as the other menu items 😕

**Comment by GramThanos** [comment]
I think I just found what causes the problem ... 
the time change on 29/10/2017 (Daylight Saving Time Ends)

**Comment by GramThanos** [comment]
It is now fixed (on latest source code, *v1.4-beta.3*).
Fixed on commit 80d87e8d830653bd5eb4a3718f53f7b1cfbc3a26

**Comment by ghost** [comment]
Haha, thanks for the quick reply and fix!

**Comment by kirienzo** [comment]
Sorry for the late reply !
Thanks for the fix, it works :)
![image](https://user-images.githubusercontent.com/6702588/31763672-404e0d70-b4bf-11e7-878e-72217ab0b4b5.png)

As for your question, i'm using Firefox 55.0.2 (64bits) on a Ubuntu 17.04

**Comment by GramThanos** [comment]
Thanks for the feedback!
