### ISSUE TITLE
language option not working

### ISSUE THREAD

**Issue by itsHusky** [GramThanos/jsCalendar#51]
When using the calendar options, the language tag only works for the language "en" (at least for me, it did). I fixed it by manually adding the "de" language into the jsCalendar.js file.

**HTML**
`<div id="my-calendar"></div>`

**JS**
```
var element = document.getElementById("my-calendar");
    // Create the calendar
    var myCalendar = jsCalendar.new({
        target : element,
        navigator : true,
        navigatorPosition : "right",
        zeroFill : true,
        monthFormat : "month",
        dayFormat : "DD",
        language : "de"
    });

   // Languages
    JsCalendar.prototype.languages = {
        // Default English language
        en : {
            // Months Names
            months : ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'],
            // Days Names
            days : ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
            // Default handlers
            _dateStringParser : function(key, date) {return JsCalendar._defaultDateStringParser(key, date, this);},
            _dayStringParser : function(key, date) {return JsCalendar._defaultDayStringParser(key, date, this);}
        },
        //manually added the german language here
        de : {
            // Months Names
            months : ['Januar', 'Februar', 'März', 'April', 'Mai', 'Juni', 'Juli', 'August', 'September', 'Oktober', 'November', 'Dezember'],
            // Days Names
            days : ['Sonntag', 'Montag', 'Dienstag', 'Mittwoch', 'Donnerstag', 'Freitag', 'Samstag'],
            // Default handlers
            _dateStringParser : function(key, date) {return JsCalendar._defaultDateStringParser(key, date, this);},
            _dayStringParser : function(key, date) {return JsCalendar._defaultDayStringParser(key, date, this);}
        },
    };`
```

**Comment by GramThanos** [comment]
Did you include the de language file?

**Comment by itsHusky** [comment]
Yes, I tried including the language file, but that didn't work unfortunately.
The thing that worked was including the language file and using the html attribute data-language in combination with the class "auto-jsCalendar". There, the german language has been found. When not setting the auto-jsCalendar class, it doesn't seem to work (at least not for me).

Best regards and thank you in advance,
Husky

**Comment by GramThanos** [comment]
I will test it.

**Comment by GramThanos** [comment]
I was not able to reproduce the problem, I edited the example languages file to create calendars dynamically too 0b350225bfaf968dbae1b4da034e309907ba5d42.
Can you test the /examples/languages.html ?

**Comment by mhollebecq** [comment]
Hello
I have also the same probleme with french language.
When trying to follow a route, I have :
-jsCalendar.lang.fr.js file exectued, successfully call `jsCalendar.addLanguage({code : 'fr',...`
-Using "DOMContendLoaded" event call back, `jsCalendar.new({language: "fr",...})` called
-`JsCalendar.addLanguage(...)` asynchronously called in jsCalendar.js file...but to late

**Comment by mhollebecq** [comment]
I have found a clean solution. In the documentation, it is said "So first you need to load the languages on the HTML's <head>." but it will only work if you have also the jsCalendar.js link in the <head> tag. If you put jsCalendar.js in the body, you have to put jsCalendar.lang.xx.js also in the body

**Comment by GramThanos** [comment]
I think the main problem is located at the asynchronous wait the library loads languages. This may delay thee loading of a language and depending on your code flow produce the problem.

I will have to patch it to work as expected.
