### ISSUE TITLE
Has anyone used this in React.js? 

### ISSUE THREAD

**Issue by Mike-Diaz** [GramThanos/jsCalendar#52]
I would like to implement this into React.js. I am using a local copy of the jsCalendar.js since I have custom functions that work with my calendar. I was using jsCalendarCreartor for my static HTML page previously, but I am having a hard time getting it ported into React. If anyone has done this it would be awesome if I could reference your process.

**Comment by GramThanos** [comment]
I am not aware of any React.js port.

**Comment by Mike-Diaz** [comment]
I'll see if I can get it working, thanks for the reply!
