### ISSUE TITLE
Suggestion : use of getFullYear() instead of getYear()

### ISSUE THREAD

**Issue by mhollebecq** [GramThanos/jsCalendar#54]
Hello
Being curious of the source code of jsCalendar, I was surprised by the use of the deprecated function "getYear". Why not use "getFullYear()" instead ? Because getFullYear seems to be supported on every browser, even the oldest version of internet explorer

**Comment by GramThanos** [comment]
Oups :P Thanks for raising an issue. We will have to patch that.

**Comment by mhollebecq** [comment]
You are welcome ;)
