### ISSUE TITLE
Suggestion: Use Intl.DateTimeFormat

### ISSUE THREAD

**Issue by paxperscientiam** [GramThanos/jsCalendar#57]
My suggestion is to use `Intl.DateTimeFormat()` to replace some external language files and maybe make timezone headaches easier to deal with.

EG:
```js
const date = new Date(Date.UTC(2020, 11, 20, 3, 23, 16, 738));
var options = { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' };
new Intl.DateTimeFormat('de-DE', options).format(date) 
// => "Samstag, 19. Dezember 2020"
```

Happy to help if you're interested

**Comment by GramThanos** [comment]
This version was supposed to be compatible also with older browsers (including IE).

But for the next version I am thinking of dropping the support for them and simplifying stuf. I will have to look into this and check the pros and cons.

**Comment by paxperscientiam** [comment]
Oh wow, no version of IE supports Intl. 

edit: @GramThanos , should i close this then?
