### ISSUE TITLE
.refresh(date) method doesn't work

### ISSUE THREAD

**Issue by thatONEjustin** [GramThanos/jsCalendar#60]
Working with an alpinejs component and using the refresh method with a date doesn't do anything. All other methods work. 

Initialization: 
```
this.calendars.first = new jsCalendar('.three-calendars', this.startDate, {
     navigator: false
});
```

Refresh:
`this.calendars.first.refresh(this.startDate);` 

I've tried the following dates with `this.startDate`:
- Fri May 21 2021 00:00:00 GMT-0500 (Central Daylight Time)
- 2021-05-25 *(throws warning about date not parsing correctly)*
- 2021/05/25 *(works on initialization but not on refresh)*

**Comment by thatONEjustin** [comment]
oh it doesn't even work in the documentation: https://gramthanos.github.io/jsCalendar/docs.html#javascript-method-refresh

**Comment by GramThanos** [comment]
Hey! In the documentation there is no date on the `refresh` call so this is why you don't see anything.

This code, based on the `examples/refresh method.html`, works just fine:
```html
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<title>jsCalendar</title>
		<meta name="description" content="jsCalendar example">
		<meta name="author" content="GramThanos">

		<!-- jsCalendar -->
		<link rel="stylesheet" type="text/css" href="../source/jsCalendar.css">
		<script type="text/javascript" src="../source/jsCalendar.js"></script>

		<!--[if lt IE 9]>
			<script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.js"></script>
		<![endif]-->
	</head>
	<body>


		<!-- Button -->
		<button id="my-button">Refresh</button>
		<!-- My calendar element -->
		<div id="my-calendar"></div>
		<!-- Create the calendar -->
		<script type="text/javascript">
			// Create the calendar
			var myCalendar = jsCalendar.new("#my-calendar");
			// Get the button
			var button = document.getElementById("my-button");
			// Add a button event
			button.addEventListener("click", function(){
				// Refresh
				//myCalendar.refresh();
				myCalendar.refresh(new Date('2021-01-31'));
			}, false);
		</script>


	</body>
</html>
```

Check on the documentation the supported formats for date: https://gramthanos.github.io/jsCalendar/docs.html#javascript-calendar-date

**Comment by thatONEjustin** [comment]
So I've loaded your example in codepen here: https://codepen.io/thatONEjustin/pen/xxqgXOL

I do understand when `myCalendar.refresh(new Date('2021-01-31'))` is executed it will switch TO the month. 

But the Calendar HTML itself never changes, the January 1st 2021 `<td>` never gets the `jsCalendar-current` class applied to it. 

further testing showed that `myCalendar.onDateRender()` is properly being called when `myCalendar.refresh()` is run. 

I set up:
```
myCalendar.onDateRender((date, element, info) => console.log(date, info.isCurrent));
```

Even with the hardcoded date January 1st, it's not being properly set as the calendar's current date
![image](https://user-images.githubusercontent.com/2763180/119034663-32873a00-b974-11eb-87c1-357a46971cdf.png)

**Comment by GramThanos** [comment]
I think you are confused. If you want to change date, you have to use the `.set(new Date("2021-01-31"))`.

**Comment by thatONEjustin** [comment]
I am somewhat confused based on what's written in the documentation:

> Refreshes the calendar, updating the HTML of the calendar  

but even if I have interacted with the calendar, it doesn't update the HTML of the calendar at all. What's the purpose of the .refresh() method?

**Comment by GramThanos** [comment]
The `refresh` method essentially renders the background information of the calendar. 

For example, the `goto` method updates the month to display variable on the background and then calls `refresh` to show the changes on the UI.

In the same way, if you change manually any calendar variable (with custom code) you can call `refresh` to sync changes with the UI.

For most users this method has no value.
