### ISSUE TITLE
Add VietNamese Language support

### ISSUE THREAD

**Issue by dienht** [GramThanos/jsCalendar#64]
Overview:
As an increasing number of users are joining our platform from Vietnam and other Vietnamese-speaking regions, it's crucial for us to enhance the user experience by providing native language support. This issue aims to discuss and implement the integration of the Vietnamese language into our platform.

Proposal:
We propose adding Vietnamese language support to our application, which includes translating all month and days into Vietnamese. By doing so, we can create a more inclusive and user-friendly environment for our Vietnamese-speaking users, ultimately expanding our reach and user base.

**Comment by dienht** [comment]
**HTML:** 
```
        <div id="calendar" data-language="vi" data-day-format="DD"></div>
```
**Create a file js and import to project.** 
```
/*
 * jsCalendar language extension
 * Add VietNamese Language support
 * Translator: Nguyen Duy Dien (dienht@github)
 */

// We love anonymous functions
(function(){

    // Get library
    var jsCalendar = window.jsCalendar;

    // If jsCalendar is not loaded
    if (typeof jsCalendar === 'undefined') {
        // If there is no language to load array
        if (typeof window.jsCalendar_language2load === 'undefined') {
            window.jsCalendar_language2load = [];
        }
        // Wrapper to add language to load list
        jsCalendar = {
            addLanguage : function (language) {
                // Add language to load list
                window.jsCalendar_language2load.push(language);
            }
        };
    }

    // Add a new language
    jsCalendar.addLanguage({
        // Language code
        code : 'vi',
        // Months of the year
        months : [
            "Tháng 1",
            "Tháng 2",
            "Tháng 3",
            "Tháng 4",
            "Tháng 5",
            "Tháng 6",
            "Tháng 7",
            "Tháng 8",
            "Tháng 9",
            "Tháng 10",
            "Tháng 11",
            "Tháng 12",
        ],
        // Days of the week
        days : [
            "CN",
            "T2",
            "T3",
            "T4",
            "T5",
            "T6",
            "T7"
        ],
    });

})();

```

**Comment by GramThanos** [comment]
Hey there. I cross checked your translations and I am not sure if they are correct.
For example, `January` seems to be `Tháng Một` not `Tháng 1`.

**Comment by dienht** [comment]
> Hey there. I cross checked your translations and I am not sure if they are correct. For example, `January` seems to be `Tháng Một` not `Tháng 1`.

"Tháng Một" is same meaning with "Tháng 1". 

![image](https://github.com/GramThanos/jsCalendar/assets/111869759/209ac982-2cf3-4784-8040-7f262ad6d403)
Wiki: https://vi.wikipedia.org/wiki/Th%C3%A1ng_m%E1%BB%99t#:~:text=Th%C3%A1ng%20M%E1%BB%99t%20(th%C3%A1ng%201)%20l%C3%A0,th%C3%A1ng%20n%C3%A0y%20l%C3%A0%20th%C3%A1ng%20m%E1%BB%99t.

This spelling is common in Vietnam:
![image](https://github.com/GramThanos/jsCalendar/assets/111869759/911cd771-baf1-4c29-abe4-16ddad2f8c4f)
