### ISSUE TITLE
Adding multiple dates to calendar

### ISSUE THREAD

**Issue by w33zy** [GramThanos/jsCalendar#8]
Is there a trick to adding multiple dates to jsCalendar?

This is what I've tried:

                // Dates
		var date = ["02/02/2017", "18/02/2017", "20/02/2017", "22/02/2017"];
		// Get the element
		var element = document.getElementById("my-calendar");
		// Create the calendar
		var calendar = jsCalendar.new(element);			
		date.map( function(day){
			calendar.set(day);
		 } );

**Comment by GramThanos** [comment]
I think that you want to `select` the days, not to `set` them.

```javascript
myCalendar.select([
    "01/02/2018",
    "02/02/2018",
    "03/02/2018",
    "05/02/2018"
]);
```

This confusion is my mistake as I deleted by mistake this part from the documentation in the last update.
I just restored it, so you can find some examples there.
https://gramthanos.github.io/jsCalendar/docs.html#more-javascript-select

**Comment by w33zy** [comment]
Thanks alot for this info. It helps alot.
